export enum Role {
  IT_USER_ADMIN = 'IT_USER_ADMIN',
  IT_SYSTEM_ADMIN = 'IT_SYSTEM_ADMIN',
  MARKET_RISK_ADMIN = 'MARKET_RISK_ADMIN',
  MARKET_RISK_REPORT_VIEWER = 'MARKET_RISK_REPORT_VIEWER'
}

export const RoleOptions: Record<Role, string> = {
  [Role.IT_USER_ADMIN]: 'IT_USER_ADMIN',
  [Role.IT_SYSTEM_ADMIN]: 'IT_USER_ADMIN',
  [Role.MARKET_RISK_ADMIN]: 'MARKET_RISK_ADMIN',
  [Role.MARKET_RISK_REPORT_VIEWER]: 'MARKET_RISK_REPORT_VIEWER',
};